# Generated by Django 5.0.7 on 2024-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoimage', models.ImageField(upload_to='settings/')),
                ('slider_image', models.ImageField(upload_to='settings/')),
                ('company_name', models.CharField(max_length=264)),
                ('mobile_number', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
            ],
        ),
    ]
