# Generated by Django 5.0.7 on 2024-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_picture', models.ImageField(upload_to='homeslides/')),
                ('title', models.CharField(max_length=264)),
            ],
        ),
    ]
