# Generated by Django 5.0.7 on 2024-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_homeslides'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideHomeSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_slide_picture', models.ImageField(upload_to='secondSection/')),
                ('title', models.CharField(blank=True, max_length=264)),
            ],
        ),
        migrations.AlterField(
            model_name='homeslides',
            name='title',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
