# Generated by Django 5.0.7 on 2024-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_sidehomeslides_alter_homeslides_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='audio',
            field=models.FileField(blank=True, upload_to='settings/'),
        ),
    ]
