# Generated by Django 5.0.7 on 2024-07-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_settings_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_me',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='office_time',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
