# Generated by Django 5.0.7 on 2024-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_settings_about_me_settings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about_me',
            field=models.TextField(max_length=264, null=True),
        ),
    ]
