# Generated by Django 5.0.7 on 2024-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_settings_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.TextField(max_length=264, null=True),
        ),
    ]
