# Generated by Django 5.0.7 on 2024-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_settings_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentSpeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
            ],
        ),
    ]
