# Generated by Django 5.0.7 on 2024-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_presidentspeach'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentspeach',
            name='speach',
            field=models.TextField(null=True),
        ),
    ]
