# Generated by Django 5.0.7 on 2024-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_presidentspeach_speach'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentspeach',
            name='image',
            field=models.ImageField(null=True, upload_to='presidentImage/'),
        ),
    ]
