# Generated by Django 5.0.7 on 2024-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_presidentspeach_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutUs/')),
                ('about_us', models.TextField()),
                ('name', models.CharField(max_length=264)),
            ],
        ),
    ]
