# Generated by Django 5.0.7 on 2024-07-30 03:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='presidentspeach',
            name='speach',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
