# Generated by Django 5.0.7 on 2024-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_alter_aboutus_about_us_alter_presidentspeach_speach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presidentspeach',
            name='speach',
            field=models.TextField(null=True),
        ),
    ]
