# Generated by Django 5.0.7 on 2024-07-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_aboutus_about_us_alter_presidentspeach_speach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('want_to_say', models.TextField(max_length=264)),
            ],
        ),
    ]
