# Generated by Django 5.0.7 on 2024-07-30 06:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_topmanagement_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmanagement',
            name='want_to_say',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
