# Generated by Django 5.0.7 on 2024-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_hazzmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazzmessage',
            name='number',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
