# Generated by Django 5.0.7 on 2024-07-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_hazzmessage_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HazzMessage',
            new_name='Hazz_Message',
        ),
    ]
