# Generated by Django 5.0.7 on 2024-07-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_agencyshould'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyShould',
            new_name='Agency_Should',
        ),
    ]
