# Generated by Django 5.0.7 on 2024-07-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_hazz_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
