# Generated by Django 5.0.7 on 2024-07-30 11:04

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_image_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('video', models.FileField(blank=True, upload_to='gallery/video/')),
                ('add_video_from_any_link', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
    ]
