# Generated by Django 5.0.7 on 2024-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='file',
            field=models.FileField(null=True, upload_to='form/'),
        ),
    ]
