# Generated by Django 5.0.7 on 2024-08-01 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_form_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
