# Generated by Django 5.0.7 on 2024-08-01 08:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_settings_baner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', ckeditor.fields.RichTextField()),
                ('picture', models.ImageField(upload_to='news/')),
                ('news_details', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
