# Generated by Django 5.0.7 on 2024-08-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_latest_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='headline',
            field=models.TextField(null=True),
        ),
    ]
