# Generated by Django 5.0.7 on 2024-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0032_alter_latest_news_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_news',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
