# Generated by Django 5.0.7 on 2024-08-03 10:22

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_latest_news_pub_date_latest_news_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='slider_image',
        ),
        migrations.AddField(
            model_name='settings',
            name='eye_frame_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='top_link_icon_image',
            field=models.ImageField(blank=True, upload_to='settings/'),
        ),
    ]
