# Generated by Django 5.0.7 on 2024-08-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_remove_settings_slider_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_inbox',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
