# Generated by Django 5.0.7 on 2024-08-14 04:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_alter_email_inbox_message_alter_form_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmanagement',
            name='joining_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_us',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='headline',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
