# Generated by Django 5.0.7 on 2024-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0036_topmanagement_joining_date_alter_aboutus_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_inbox',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topmanagement',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
