# Generated by Django 5.0.7 on 2024-08-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0037_alter_email_inbox_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_inbox',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='audio',
            field=models.FileField(upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='top_link_icon_image',
            field=models.ImageField(upload_to='settings/'),
        ),
    ]
